# Generated by Django 5.0.6 on 2026-09-06 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='resumes.resume'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['resume', 'job'], name='matching_ma_resume__f2b09a_idx'),
        ),
    ]
