import React, { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import Navbar from '../components/Navbar'
import api from '../api/axios'

const initial = { title: '', company: '', location: '', employment_type: 'full_time', experience_required: '', salary: '', description: '', responsibilities: '', education_requirements: '', required_skills: '', preferred_skills: '', status: 'published' }

export default function RecruiterJobForm() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [form, setForm] = useState(initial)
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)
  useEffect(() => { if (id) api.get(`/jobs/${id}/`).then(({ data }) => setForm((current) => ({ ...current, ...data, required_skills: (data.job_skills || []).filter((skill) => skill.required).map((skill) => skill.skill.name).join(', '), preferred_skills: (data.job_skills || []).filter((skill) => !skill.required).map((skill) => skill.skill.name).join(', ') }))).catch(() => setError('Job could not be loaded.')) }, [id])
  function update(field, value) { setForm((current) => ({ ...current, [field]: value })) }
  async function submit(event) { event.preventDefault(); setSaving(true); setError(''); try { if (id) await api.patch(`/jobs/${id}/`, form); else await api.post('/applications/recruiter/jobs/', form); navigate('/recruiter/jobs') } catch (err) { const errors = err.response?.data?.errors || {}; const detail = Object.values(errors).flat().join(' '); setError(err.response?.data?.message || detail || 'Please check the form fields.') } finally { setSaving(false) } }
  return <div><Navbar /><main className="max-w-3xl mx-auto px-6 py-10"><Link to="/recruiter/jobs" className="text-sm text-primary-600">← My jobs</Link><h1 className="text-3xl font-bold mt-4">{id ? 'Edit job' : 'Post a new job'}</h1>{error && <p className="bg-red-50 text-red-600 p-3 rounded-md text-sm mt-5">{error}</p>}<form onSubmit={submit} className="bg-white border rounded-xl p-6 mt-6 grid gap-4"><Field label="Job title" value={form.title} onChange={(v) => update('title', v)} required /><div className="grid md:grid-cols-2 gap-4"><Field label="Company" value={form.company} onChange={(v) => update('company', v)} required /><Field label="Location" value={form.location} onChange={(v) => update('location', v)} /></div><div className="grid md:grid-cols-2 gap-4"><Field label="Experience required" value={form.experience_required} onChange={(v) => update('experience_required', v)} /><Field label="Salary" value={form.salary} onChange={(v) => update('salary', v)} /></div><label className="text-sm font-medium">Employment type<select value={form.employment_type} onChange={(e) => update('employment_type', e.target.value)} className="block w-full border rounded-md px-3 py-2 mt-1"><option value="full_time">Full time</option><option value="part_time">Part time</option><option value="contract">Contract</option><option value="internship">Internship</option><option value="remote">Remote</option></select></label><Field label="Required skills (comma separated)" value={form.required_skills} onChange={(v) => update('required_skills', v)} placeholder="Python, Django, PostgreSQL" required /><Field label="Preferred skills (comma separated)" value={form.preferred_skills} onChange={(v) => update('preferred_skills', v)} placeholder="Docker, AWS" /><TextArea label="Job description" value={form.description} onChange={(v) => update('description', v)} required /><TextArea label="Responsibilities" value={form.responsibilities} onChange={(v) => update('responsibilities', v)} /><Field label="Education requirements" value={form.education_requirements} onChange={(v) => update('education_requirements', v)} /><label className="text-sm font-medium">Status<select value={form.status} onChange={(e) => update('status', e.target.value)} className="block w-full border rounded-md px-3 py-2 mt-1"><option value="published">Publish now</option><option value="draft">Save draft</option></select></label><button disabled={saving} className="bg-primary-600 text-white py-3 rounded-md font-medium">{saving ? 'Saving...' : id ? 'Update job' : 'Create job'}</button></form></main></div>
}
function Field({ label, value, onChange, required }) { return <label className="text-sm font-medium">{label}<input required={required} value={value || ''} onChange={(e) => onChange(e.target.value)} className="block w-full border rounded-md px-3 py-2 mt-1 font-normal" /></label> }
function TextArea({ label, value, onChange, required }) { return <label className="text-sm font-medium">{label}<textarea required={required} rows="6" value={value || ''} onChange={(e) => onChange(e.target.value)} className="block w-full border rounded-md px-3 py-2 mt-1 font-normal" /></label> }
